name: CI-build-and-push-image-for-dotnetapp

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/case_study_6_michiel_van_loy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/case_study_6_michiel_van_loy:${{ github.run_number }}

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}case_study_6_michiel_van_loy:latest
